# config.yaml
backend:
  host: 0.0.0.0
  port: 8000
  frontend_origins:
    - http://localhost:3000
    - http://localhost:5173

vectorstore:
  docs_path: ./backend/app/knowledge/docs
  store_path: ./backend/app/knowledge/vectorstore

ollama:
  api_url: http://ollama:11434/api/generate
  model: deepseek-r1:latest

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
