services:
  # اگر می‌خواهید از کانتینر Ollama با مدل‌های میزبان استفاده کنید:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama   # استفاده از مدل‌های محلی

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: edris-backend
    env_file:
      - backend/.env
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/generate
    volumes:
      - ./backend/app/knowledge/docs:/app/app/knowledge/docs
      - ./backend/app/knowledge/vectorstore:/app/app/knowledge/vectorstore
      - ./config.yaml:/app/config.yaml:ro
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: edris-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
