services:
  # اگر می‌خواهید از کانتینر Ollama با مدل‌های میزبان استفاده کنید:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/custom_models
    ports:
      - "11435:11434"
    volumes:
      - /Users/amirpartovi/.ollama:/root/.ollama:ro
      - /Users/amirpartovi/.ollama/custom_models:/root/.ollama/custom_models
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    container_name: edris-backend
    env_file:
      - backend/.env
    volumes:
      - ./backend/app/knowledge/docs:/app/knowledge/docs
      - ./backend/app/knowledge/vectorstore:/app/knowledge/vectorstore
      - ./config.yaml:/app/config.yaml:ro
    depends_on:
      - ollama

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: edris-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
